name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Google Cloud Platform (GCP) CLI - gcloud
      uses: actions-hub/gcloud@278.0.0
      with:
        # Project id
        PROJECT_ID:${{secrets.GCLOUD_PROJECT_ID}}
        # GCP authorization credentials
        APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
